"""Build the locale-aware goal wizard data from its canonical JSON source."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/governance/goal-templates.json"
OUTPUT = ROOT / "site/goal-templates.js"
LOCALES = ("en", "zh", "es", "ja", "ko", "de", "zh-tw", "fr")
GOALS = ("language", "work", "research", "interview", "task", "codex")


def load_source() -> dict[str, Any]:
    value = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or value.get("schema_version") != "1":
        raise ValueError("goal template source must be schema version 1")
    goals = value.get("goals")
    if not isinstance(goals, dict) or set(goals) != set(LOCALES):
        raise ValueError(f"goal template source must contain exactly: {', '.join(LOCALES)}")
    for locale in LOCALES:
        localized = goals[locale]
        if not isinstance(localized, dict) or set(localized) != set(GOALS):
            raise ValueError(f"{locale} goal templates must contain exactly: {', '.join(GOALS)}")
        for goal in GOALS:
            record = localized[goal]
            if not isinstance(record, dict):
                raise ValueError(f"{locale}/{goal} must be an object")
            fields = record.get("fields")
            if not isinstance(fields, list):
                raise ValueError(f"{locale}/{goal}.fields must be a list")
            keys: set[str] = set()
            for field in fields:
                if not isinstance(field, dict) or not isinstance(field.get("key"), str):
                    raise ValueError(f"{locale}/{goal} contains an invalid field")
                if field["key"] in keys:
                    raise ValueError(f"{locale}/{goal} repeats field {field['key']}")
                keys.add(field["key"])
                for name in ("label", "placeholder"):
                    if not isinstance(field.get(name), str) or not field[name].strip():
                        raise ValueError(f"{locale}/{goal}/{field['key']} is missing {name}")
            if not isinstance(record.get("template"), str) or not record["template"].strip():
                raise ValueError(f"{locale}/{goal} is missing template text")
            if not isinstance(record.get("path"), str) or not record["path"].strip():
                raise ValueError(f"{locale}/{goal} is missing Reader path")
    return value


def render(value: dict[str, Any]) -> str:
    payload = {
        "schema_version": value["schema_version"],
        "generator": "scripts/build_goal_templates.py",
        "goals": value["goals"],
    }
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    return "/* Generated by scripts/build_goal_templates.py. Do not edit by hand. */\nwindow.GOAL_TEMPLATES = " + body + ";\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated JS is stale")
    args = parser.parse_args()
    try:
        expected = render(load_source())
    except (OSError, UnicodeError, json.JSONDecodeError, TypeError, ValueError) as exc:
        print("GOAL_TEMPLATES_FAILED")
        print(f"- {exc}")
        return 1
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("GOAL_TEMPLATES_FAILED")
            print(f"- generated output is stale or missing: {OUTPUT.relative_to(ROOT)}")
            print("- run: python scripts/build_goal_templates.py")
            return 1
        print(f"GOAL_TEMPLATES_OK locales={len(LOCALES)} goals={len(GOALS)}")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"GOAL_TEMPLATES_BUILT output={OUTPUT.relative_to(ROOT)} locales={len(LOCALES)} goals={len(GOALS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
