"""Build the canonical title projection consumed by book reading surfaces."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
NAVIGATION_FILE = ROOT / "docs/governance/book-navigation.yaml"
OUTPUT_FILE = ROOT / "book/title-map.json"
ENGLISH_TOC = ROOT / "book/table-of-contents-EN.md"
ENGLISH_HEADING_RE = re.compile(r"(?m)^### Chapter (\d+) — .+$")
LOCALE_KEYS = ("en", "zh", "es", "ja", "ko", "de")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def expected_title_map(navigation: dict[str, Any]) -> dict[str, Any]:
    """Project chapter title roles without creating another editable source."""

    chapters = navigation.get("chapters")
    if not isinstance(chapters, list):
        raise ValueError("book navigation must contain a chapters list")
    records: list[dict[str, Any]] = []
    for item in chapters:
        if not isinstance(item, dict):
            raise ValueError("book navigation chapters must contain objects")
        records.append(
            {
                "id": item["id"],
                "number": item["number"],
                "part": item["part"],
                "canonical": {key: item[f"canonical_title_{key}"] for key in LOCALE_KEYS},
                "display": {key: item[f"title_{key}"] for key in LOCALE_KEYS},
            }
        )
    return {
        "schema_version": "1",
        "generated_by": "scripts/build_book_title_map.py",
        "generator_notice": "Generated by scripts/build_book_title_map.py. Do not edit by hand.",
        "source": "docs/governance/book-navigation.yaml",
        "title_roles": {
            "canonical": "Exact chapter H1 body; search title and source identity.",
            "display": "Compact title for tables of contents, rails, and adjacent navigation.",
        },
        "chapters": records,
    }


def load_title_map(path: Path = OUTPUT_FILE) -> dict[str, Any]:
    value = load_json(path)
    if not isinstance(value, dict):
        raise ValueError(f"title map must be an object: {path.relative_to(ROOT)}")
    return value


def assert_current_title_map(title_map: dict[str, Any], navigation: dict[str, Any]) -> None:
    if title_map != expected_title_map(navigation):
        raise ValueError("title map is stale or malformed; run: python scripts/build_book_title_map.py")


def records_by_id(title_map: dict[str, Any]) -> dict[str, dict[str, Any]]:
    chapters = title_map.get("chapters")
    if not isinstance(chapters, list):
        raise ValueError("title map must contain a chapters list")
    records: dict[str, dict[str, Any]] = {}
    for item in chapters:
        if not isinstance(item, dict) or not isinstance(item.get("id"), str):
            raise ValueError("title map chapters must have string IDs")
        if item["id"] in records:
            raise ValueError(f"title map chapter ID is duplicated: {item['id']}")
        for field in ("number", "part", "canonical", "display"):
            if field not in item:
                raise ValueError(f"title map chapter is missing {field}: {item['id']}")
        for role in ("canonical", "display"):
            value = item[role]
            if not isinstance(value, dict) or not all(
                isinstance(value.get(locale), str) and value[locale].strip()
                for locale in LOCALE_KEYS
            ):
                raise ValueError(f"title map {role} titles must be non-empty for all six locales: {item['id']}")
        records[item["id"]] = item
    return records


def render(title_map: dict[str, Any]) -> str:
    return json.dumps(title_map, ensure_ascii=False, indent=2) + "\n"


def expected_toc(text: str, title_map: dict[str, Any]) -> str:
    records = list(records_by_id(title_map).values())
    expected_by_number = {int(item["number"]): str(item["display"]["en"]) for item in records}
    seen: set[int] = set()

    def replace(match: re.Match[str]) -> str:
        number = int(match.group(1))
        if number not in expected_by_number:
            raise ValueError(f"TOC names an unregistered chapter: {number}")
        if number in seen:
            raise ValueError(f"TOC duplicates a chapter heading: {number}")
        seen.add(number)
        return f"### Chapter {number} — {expected_by_number[number]}"

    updated = ENGLISH_HEADING_RE.sub(replace, text)
    if seen != set(expected_by_number):
        raise ValueError("TOC title projection must contain each registered chapter once")
    return updated


def stale_outputs(title_map: dict[str, Any]) -> list[str]:
    stale: list[str] = []
    expected_map = render(title_map)
    if not OUTPUT_FILE.is_file() or OUTPUT_FILE.read_text(encoding="utf-8") != expected_map:
        stale.append(str(OUTPUT_FILE.relative_to(ROOT)))
    if not ENGLISH_TOC.is_file():
        stale.append(str(ENGLISH_TOC.relative_to(ROOT)))
        return stale
    actual = ENGLISH_TOC.read_text(encoding="utf-8")
    if expected_toc(actual, title_map) != actual:
        stale.append(str(ENGLISH_TOC.relative_to(ROOT)))
    return stale


def write_outputs(title_map: dict[str, Any]) -> int:
    changed = 0
    expected_map = render(title_map)
    if not OUTPUT_FILE.is_file() or OUTPUT_FILE.read_text(encoding="utf-8") != expected_map:
        OUTPUT_FILE.write_text(expected_map, encoding="utf-8", newline="\n")
        changed += 1
    actual = ENGLISH_TOC.read_text(encoding="utf-8")
    expected = expected_toc(actual, title_map)
    if actual != expected:
        ENGLISH_TOC.write_text(expected, encoding="utf-8", newline="\n")
        changed += 1
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated title outputs are stale")
    args = parser.parse_args()
    try:
        navigation = load_json(NAVIGATION_FILE)
        if not isinstance(navigation, dict):
            raise ValueError("book navigation must be an object")
        title_map = expected_title_map(navigation)
        records_by_id(title_map)
        stale = stale_outputs(title_map)
    except (OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        print("BOOK_TITLE_MAP_FAILED")
        print(f"- {exc}")
        return 1

    if args.check and stale:
        print("BOOK_TITLE_MAP_FAILED")
        for path in stale:
            print(f"- generated output is stale or missing: {path}")
        print("- run: python scripts/build_book_title_map.py")
        return 1
    if stale:
        changed = write_outputs(title_map)
        print(f"BOOK_TITLE_MAP_BUILT outputs={changed} chapters={len(title_map['chapters'])}")
    else:
        print(f"BOOK_TITLE_MAP_OK chapters={len(title_map['chapters'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
