"""Repository-level regression contract for Reader Lab navigation and fallback."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import build_site_search_index as search_index


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "site/locale-manifest.js"
READER_PATH = ROOT / "site/reader.js"
LOCALE_MATRIX_PATH = ROOT / "docs/governance/locale-matrix.yaml"
MANIFEST_PREFIX = "/* Generated by scripts/build_site_locale_manifest.py. Do not edit by hand. */\nwindow.CODEX_LOCALE_MANIFEST = "


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def load_manifest() -> dict:
    source = MANIFEST_PATH.read_text(encoding="utf-8")
    require(source.startswith(MANIFEST_PREFIX), "locale manifest header or assignment changed")
    require(source.rstrip().endswith(";"), "locale manifest assignment is not terminated")
    return json.loads(source[len(MANIFEST_PREFIX) :].strip().removesuffix(";"))


def main() -> int:
    try:
        manifest = load_manifest()
        labs = manifest["lab_navigation"]["labs"]
        require(len(labs) == 18, f"Reader manifest projects {len(labs)} Labs instead of 18")
        require([lab["number"] for lab in labs] == list(range(1, 19)), "Lab numbers are not the complete 1-18 sequence")
        require(labs[0]["content_id"] == "lab-001-first-safe-task", "Lab 001 is not the first Reader entry")
        require(labs[8]["content_id"] == "lab-009-engineering-lifecycle", "Lab 009 is not the middle fixture")
        require(labs[-1]["content_id"] == "lab-018-language-transfer", "Lab 018 is not the last Reader entry")

        reader = READER_PATH.read_text(encoding="utf-8")
        for required in (
            "function labForSelection(selection)",
            "function labPath(lab)",
            "function labProgressLabel(lab)",
            "Catalog order, not a prerequisite chain",
            "const currentLab = labForSelection(selection);",
            "if (!pagination) return;",
            "if (!bookNav || !bookProgress || !chapterList)",
            "updateLabLink(mobilePrevious, previous, 'previous');",
            "updateLabLink(mobileNext, next, 'next');",
            "updateLabPagination(previousLink, previousTitle, previous, 'previous');",
            "updateLabPagination(nextLink, nextTitle, next, 'next');",
            "const generatedBlockStart = line.trim().match(/^<!--\\s*(chapter-navigation|lab-navigation|language-switcher):start\\s*-->$/i);",
            "const h1BeforeFrontMatter = fragment.childNodes.length === 1 && fragment.firstChild?.tagName === 'H1';",
        ):
            require(required in reader, f"Reader Lab contract is missing: {required}")
        require(
            "if (!bookNav || !bookProgress || !chapterList || !pagination) return;" not in reader,
            "Lab navigation is still coupled to chapter-only rail nodes",
        )
        require("index === 0 && line.trim() === '---'" not in reader, "front matter still fails after a content identity comment")

        for search_fixture in (
            "<!-- content_id: fixture -->\n\n---\nid: fixture\ntitle: Hidden\n---\n\n# Visible title\n\nVisible body.\n",
            "<!-- content_id: fixture -->\n\n# Visible title\n\n---\nid: fixture\ntitle: Hidden\n---\n\nVisible body.\n",
        ):
            search_body = search_index.source_body(search_fixture)
            require(search_body.startswith("# Visible title"), "search index exposes front matter around the first H1")
            require("id: fixture" not in search_body, "search index retained front-matter metadata")
        require("${generatedBlockKind}:end" in reader, "Reader does not strip matching generated metadata blocks")

        matrix = json.loads(LOCALE_MATRIX_PATH.read_text(encoding="utf-8"))
        records = {record["content_id"]: record for record in matrix["content"]}
        fallback_routes = 0
        for number in range(1, 19):
            prefix = f"lab-{number:03d}-"
            content_id = next((key for key in records if key.startswith(prefix)), None)
            require(content_id is not None, f"locale matrix is missing Lab {number:03d}")
            for locale in ("ZH", "ES", "JA", "KO", "DE"):
                localized = records[content_id]["locales"][locale]
                if (ROOT / localized["path"]).exists():
                    continue
                fallback_routes += 1
                require(localized["translation_status"] == "not-started", f"{content_id} {locale} is not fallback-only")
                require(localized["coverage"] == "route-only", f"{content_id} {locale} overstates translation coverage")
                require("English" in localized.get("reason", ""), f"{content_id} {locale} lacks an explicit English fallback reason")
    except (AssertionError, KeyError, OSError, UnicodeError, ValueError, StopIteration) as exc:
        print("READER_LAB_NAVIGATION_TESTS_FAILED")
        print(f"- {exc}")
        return 1

    print(f"READER_LAB_NAVIGATION_TESTS_OK labs=18 boundaries=3 fallback_routes={fallback_routes}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
