"""Validate the public page's language contract and translation coverage."""

from __future__ import annotations

import re
import sys
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "site/index.html"
APP = ROOT / "site/app.js"
GENERATED = ROOT / "site/learning-path-data.js"
LOCALE_MANIFEST = ROOT / "site/locale-manifest.js"
LOCALE_TOKENS = {"en", "zh", "es", "ja", "ko", "de"}
STATUS = ROOT / "docs/governance/content-status.yaml"


def keys_for(block: str, expected: set[str]) -> set[str]:
    """Find only unquoted object keys, avoiding colons inside copy strings."""
    return {
        key
        for key in expected
        if re.search(rf"(?:^|,)\s*{re.escape(key)}\s*:", block, re.MULTILINE)
    }


def translation_keys(app: str, language: str, html_keys: set[str]) -> set[str]:
    """Collect keys from the primary dictionary and additive translation blocks."""
    blocks: list[str] = []
    if language == "en":
        match = re.search(r"\n  en: \{(?P<body>.*?)\n  \},\n  zh: \{", app, re.DOTALL)
    else:
        match = re.search(r"\n  zh: \{(?P<body>.*?)\n  \}\n\};", app, re.DOTALL)
    if match:
        blocks.append(match.group("body"))
    blocks.extend(
        re.findall(
            rf"Object\.assign\(copy\.{language}, \{{(?P<body>.*?)\}}\);",
            app,
            re.DOTALL,
        )
    )
    return set().union(*(keys_for(block, html_keys) for block in blocks)) if blocks else set()


def load_generated_manifest() -> dict:
    text = LOCALE_MANIFEST.read_text(encoding="utf-8")
    marker = "window.CODEX_LOCALE_MANIFEST ="
    if marker not in text:
        raise ValueError("manifest assignment marker is missing")
    payload = text.split(marker, 1)[1].strip().rstrip(";")
    value = json.loads(payload)
    if not isinstance(value, dict):
        raise ValueError("manifest payload must be an object")
    return value


def local_target_from_href(href: str) -> str | None:
    target = href.split("#", 1)[0].split("?", 1)[0]
    if not target.startswith("../"):
        return None
    return target[3:]


def main() -> int:
    errors: list[str] = []
    manifest: dict = {}
    html = HTML.read_text(encoding="utf-8")
    app = APP.read_text(encoding="utf-8")
    if not GENERATED.is_file():
        errors.append("generated learning-path data is missing; run scripts/build_learning_path_site.py")
    elif "Generated by scripts/build_learning_path_site.py" not in GENERATED.read_text(encoding="utf-8"):
        errors.append("generated learning-path data must carry its generator marker")
    if not LOCALE_MANIFEST.is_file():
        errors.append("generated locale manifest is missing; run scripts/build_site_locale_manifest.py")
    else:
        manifest_text = LOCALE_MANIFEST.read_text(encoding="utf-8")
        if "Generated by scripts/build_site_locale_manifest.py" not in manifest_text:
            errors.append("generated locale manifest must carry its generator marker")
        manifest_tokens = set(re.findall(r'"([a-z]{2})": \{\n\s+"suffix": "(?:EN|ZH|ES|JA|KO|DE)"', manifest_text))
        if manifest_tokens != LOCALE_TOKENS:
            errors.append(f"locale manifest must contain exactly: {', '.join(sorted(LOCALE_TOKENS))}")
        for source in ("docs/governance/locale-matrix.yaml", "docs/governance/content-status.yaml"):
            if source not in manifest_text:
                errors.append(f"locale manifest source is missing: {source}")
        try:
            manifest = load_generated_manifest()
        except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
            manifest = {}
            errors.append(f"locale manifest cannot be parsed: {exc}")
        if manifest:
            if set(manifest.get("locales", {})) != LOCALE_TOKENS:
                errors.append("locale manifest locale records do not match the six registered tokens")
            counts = manifest.get("routed_status_counts")
            if counts != {"chapters": 22, "labs": 18}:
                errors.append("locale manifest must cover 22 chapters and 18 labs from content-status")
            aliases = manifest.get("aliases", {})
            for section, prefix in (("chapters", "chapter-"), ("labs", "lab-")):
                try:
                    status = json.loads(STATUS.read_text(encoding="utf-8"))
                    expected_ids = {
                        item["id"]
                        for item in status[section]["items"]
                        if isinstance(item, dict) and isinstance(item.get("id"), str)
                    }
                except (OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError):
                    expected_ids = set()
                missing = sorted(item_id for item_id in expected_ids if item_id.startswith(prefix) and item_id not in aliases)
                if missing:
                    errors.append(f"locale manifest is missing {section} aliases: {', '.join(missing)}")

    if not re.search(r"<html\s+lang=\"en\"", html):
        errors.append("site/index.html must default to lang=\"en\"")
    if "data-language-toggle" not in html:
        errors.append("language toggle is missing")
    menu_tokens = set(re.findall(r'data-language-option="([a-z]{2})"', html))
    if menu_tokens != LOCALE_TOKENS:
        errors.append(f"language menu must expose exactly: {', '.join(sorted(LOCALE_TOKENS))}")
    if "data-locale-banner" not in html or "data-locale-banner-text" not in html:
        errors.append("visible locale fallback banner is missing")
    if "URLSearchParams" not in app or "get('lang')" not in app or "searchParams.set('lang'" not in app or "localStorage" not in app:
        errors.append("language state must support a shareable lang parameter and localStorage preference")
    if "document.documentElement.lang" not in app:
        errors.append("language switching must update document.documentElement.lang")
    for marker in ("CODEX_LOCALE_MANIFEST", "contentFor", "localizedContentHref", "data-locale-fallback"):
        if marker not in app:
            errors.append(f"locale-aware link routing marker is missing: {marker}")

    html_keys = set(re.findall(r'data-i18n="([^"]+)"', html))
    for attribute_value in re.findall(r'data-i18n-attr="([^"]+)"', html):
        for entry in attribute_value.split(";"):
            parts = entry.split(":", 1)
            if len(parts) == 2:
                html_keys.add(parts[1])

    en_match = re.search(r"\n  en: \{(?P<body>.*?)\n  \},\n  zh: \{", app, re.DOTALL)
    zh_match = re.search(r"\n  zh: \{(?P<body>.*?)\n  \}\n\};", app, re.DOTALL)
    if not en_match or not zh_match:
        errors.append("translation dictionary could not be located")
        english_keys = set()
        chinese_keys = set()
    else:
        english_keys = translation_keys(app, "en", html_keys)
        chinese_keys = translation_keys(app, "zh", html_keys)
        if not english_keys:
            errors.append("English translation dictionary is empty or malformed")
        if not chinese_keys:
            errors.append("Chinese translation dictionary is empty or malformed")
        for language, keys in (("en", english_keys), ("zh", chinese_keys)):
            for key in sorted(html_keys - keys):
                errors.append(f"{language} dictionary is missing HTML key: {key}")

    if manifest:
        path_index = manifest.get("path_index", {})
        routed_paths = {
            path
            for content in manifest.get("contents", {}).values()
            if isinstance(content, dict) and content.get("kind") in {"chapter", "lab"}
            for locale in (content.get("locales", {}) or {}).values()
            if isinstance(locale, dict) and isinstance(locale.get("path"), str)
            for path in [locale["path"]]
        }
        routed_paths.update(
            path
            for content in manifest.get("contents", {}).values()
            if isinstance(content, dict)
            for path in content.get("legacy_paths", [])
            if isinstance(path, str)
        )
        for href in re.findall(r'<a\b[^>]*\bhref="([^"]+)"', html):
            target = local_target_from_href(href)
            is_routed_reader_file = (
                target
                and (target.startswith("book/chapters/") or target.startswith("book/labs/"))
                and target.endswith(".md")
                and not Path(target).name.upper().startswith("README")
            )
            if is_routed_reader_file:
                if target not in routed_paths or path_index.get(target) is None:
                    errors.append(f"site chapter/lab link is not indexed by locale manifest: {target}")
        learning_data = GENERATED.read_text(encoding="utf-8") if GENERATED.is_file() else ""
        for item_id in re.findall(r'"id":\s*"((?:chapter|lab)-[^"]+)"', learning_data):
            if item_id not in manifest.get("aliases", {}):
                errors.append(f"learning-path item is not indexed by locale manifest: {item_id}")

    if errors:
        print("VALIDATION_FAILED")
        for error in errors:
            print(f"- {error}")
        return 1

    print(f"VALIDATION_OK html_keys={len(html_keys)} translated_keys={len(english_keys)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
